### ISSUE TITLE
Big fps drops

### ISSUE THREAD

**Issue by Vexonek** [Voxla/midnightlurker#2]
Hey, I have noticed that normaly my pc can get like 200fps on moded mc but when i add the newest version of ur mod it sometimes drops under 60. So can you try fix it ?

**Comment by Voxla** [comment]
I'm currently working on a version of the mod (1.2.2 and up); once that is released, let me know if you still get the FPS drops since I introduced a new spawning system that should hopefully help with that sort of thing.
And if you are still getting FPS drops when you have the 1.2.2 version, I'll see if I can fix it.
