### ISSUE TITLE
Crashes on latest version

### ISSUE THREAD

**Issue by mbfexer** [Voxla/midnightlurker#3]
Im making a modpack with this in it and when i load a world i get a error saying The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null

**Comment by ConqAra** [comment]
Getting same thing. Log: [https://mclo.gs/oGR1tnD](https://mclo.gs/oGR1tnD)

**Comment by Voxla** [comment]
I would ask if you have GeckoLib installed, but I'm pretty sure you do since you were able to go into a world and it would usually stop you when you load into MC.
Did you have a previous version installed, like 1.1.5? If so, then that might be why. because I recently updated the config and the config doesn't update itself (which I'm going to have to implement). If you did update the mod and have the old config, I would suggest deleting the old config. Though seeing as how you're making a modpack and you didn't say anything about updating the mod's version or anything, I don't know.

I'll try to look into the error for now and hope you get back to me with a response at some point.

**Comment by mbfexer** [comment]
I went in to the config and deleted and now it works fine
