### ISSUE TITLE
Tick freeze with world generation in 1.19.2 - 2.1.5 / 2.1.1 / 2.0.8 / 2.0.4 / 2.0.0

### ISSUE THREAD

**Issue by Spid3rdr4gon** [Voxla/midnightlurker#6]
Someone else already brought this to your attention but ive encountered this problem as well and can confirm it does happen.
The problem seems to be related to structures being generated since it was easily reproducable using the /locate structure command and then tping to the structure the game otherwise ran fine when not exploring (and without generating structures). the tp then is not even executed the game just soft freezes (tick speed) so no more chunks are loaded and nothing can be interacted with anymore. The game also cannot properly close itself in this state.

Since there is no crash, I dont have any crash report to share neither does the log show anything that might be helpful.

I also did some further testing on the issue and determined that the issue is appearent since version 2.0.0 and onward. It does not occur in older versions.

I hope this is helpful.

I think that modders nowadays do not get enough recognition for their hard work so keep it up and dont stress yourself too much <3
Merry X-Mas and a happy new year.

**Comment by Voxla** [comment]
I believe the issue was how I made the Shapeshifter spawn initially.
The problem has been fixed in version 2.1.8 and up (or, well, it should be). If it isn't, let me know.

Thank you for the whole breakdown of the problem and what not. Feedback is always great to receive, so I know if something is broken and all that.

Merry Christmas and a Happy New Year to you as well.
